version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    volumes:
      - .:/var/www/html           # Monta o diretório local no container
    ports:
      - "8080:80"                 # Mapeia a porta 80 do container para 8080 no host
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"               # Porta padrão do MySQL
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - app_network

volumes:
  dbdata:

networks:
  app_network:
    driver: bridge
